apiVersion: kuma.io/v1alpha1
kind: Mesh
metadata:
  annotations:
    k8s.kuma.io/mesh-defaults-generated: 'true'
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"kuma.io/v1alpha1","kind":"Mesh","metadata":{"annotations":{},"name":"default"},"spec":{"logging":{"backends":[{"conf":{"path":"/tmp/access.log"},"name":"file","type":"file"}],"defaultBackend":"file"},"mtls":{"backends":[{"conf":{"caCert":{"RSAbits":2048,"expiration":"10y"}},"dpCert":{"rotation":{"expiration":"1d"}},"name":"ca-1","type":"builtin"}],"enabledBackend":"ca-1"},"networking":{"outbound":{"passthrough":true}},"routing":{"localityAwareLoadBalancing":true}}}
  creationTimestamp: '2022-03-25T17:39:10Z'
  generation: 4
  name: default
  resourceVersion: '588958747'
  uid: b9852910-1e61-4080-8ca2-1603bd13a2cd
spec:
  logging:
    backends:
      - conf:
          path: /tmp/access.log
        name: file
        type: file
    defaultBackend: file
  metrics:
    backends:
      - conf:
          path: /metrics
          port: 5670
          tags:
            kuma.io/service: dataplane-metrics
        name: prometheus-1
        type: prometheus
    enabledBackend: prometheus-1
  mtls:
    backends:
      - conf:
          caCert:
            RSAbits: 2048
            expiration: 10y
        dpCert:
          rotation:
            expiration: 1d
        name: ca-1
        type: builtin
    enabledBackend: ca-1
  networking:
    outbound:
      passthrough: true
  routing:
    localityAwareLoadBalancing: true
