# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
fail_fast: false
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0
    hooks:
      - id: check-added-large-files
        name: Block large file additions
      - id: check-json
        name: Validate JSON
        types:
          - json
      - id: check-merge-conflict
        name: Ensure all merges resolved
      - id: destroyed-symlinks
        name: Validate symbolic links
      - id: detect-private-key
        name: Check for private keys
      - id: end-of-file-fixer
        name: Fix end of file
      - id: fix-byte-order-marker
        name: Remove byte-order marker
      - id: no-commit-to-branch
        name: Prevent accidental commits
      - id: pretty-format-json
        name: Format JSON
        args:
          - --autofix
        types:
          - json
      - id: trailing-whitespace
        name: Ensure trailing whitespace

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.6.2
    hooks:
      - id: prettier
        name: Format content
        types:
          - markdown

  - repo: https://github.com/sirosen/texthooks
    rev: 0.5.0
    hooks:
      - id: fix-smartquotes
  # - repo: https://github.com/DavidAnson/markdownlint-cli2
  #   # Too many errors right now.
  #   rev: v0.4.0
  #   hooks:
  #     - id: markdownlint-cli2
  #       name: Check Markdown
